#include "work.h"

const char* GetErrInfo(T_I32 icode)
{
	static const char* pnull = "NULL";
	static const struct MSGCODE
	{
		T_I32 icode;       ///< 错误码
		const char* sdes;  ///< 错误描述 
	} errcode[] = {      //公用
		{SIPE_OK, "OK"},
		{SIPE_ERR, "ERROR"},
		{SIPE_ERRHANDLE, "INVALID_SIPHANDLE"},

		// TCP通讯层
		{SIPE_TCPCONNECTERR, "SIPE_TCPCONNECTERR"},
		{SIPE_PROXY_CONNECTERR, "SIPE_PROXY_CONNECTERR"},
		{SIPE_PROXY_AUTHERR, "SIPE_PROXY_AUTHERR"},
		{SIPE_DISCONNECT, "SIPE_DISCONNECT"},
		{SIPE_TCPIOERR, "SIPE_TCPIOERR"},

		// TCP消息层
		{SIPE_TCPMSGERR, "SIPE_TCPMSGERR"},
		{SIPE_TIMEOUT, "SIPE_TIMEOUT"},

		//消息传输层错误
		{SIPE_PKGFMT, "SIPE_PKGFMT"},

		//协议层
		{SIPE_PKGCODE, "SIPE_PKGCODE"},
		{SIPE_PKGDATA, "SIPE_PKGDATA"},
		{SIPE_ASYNCONNECTOK, "SIPE_ASYNCONNECTOK"},
		{SIPE_ASYNCONNECTERR, "SIPE_ASYNCONNECTERR"},

		//应用层
		{SIPE_VERSION, "SIPE_VERSION"},
		{SIPE_NOUSER, "SIPE_NOUSER"},
		{SIPE_USERAUTH, "SIPE_USERAUTH"},
		{SIPE_NOPOWER, "SIPE_NOPOWER"},
		{SIPE_NOTAG, "SIPE_NOTAG"},
		{SIPE_NODATA, "SIPE_NODATA"},
		{SIPE_MSGTYPE, "SIPE_MSGTYPE"},
		{SIPE_MSGSIZE, "SIPE_MSGSIZE"},

		{SIPE_DATALINE, "SIPE_DATALINE"},
		{SIPE_DSLCONFULL, "SIPE_DSLCONFULL"},

		{SIPE_TAGMSGSEQNO, "SIPE_TAGMSGSEQNO"},

		{SIPE_CONNECTFULL, "SIPE_CONNECTFULL"},
		{SIPE_SSCFULL, "SIPE_SSCFULL"},

		{SIPE_ERRARGS, "SIPE_ERRARGS"},
		{SIPE_DSLMAINEXIST, "SISIPE_DSLMAINEXIST"},
		{SIPE_SVRMEMERR, "SIPE_SVRMEMERR"},

		{SIPE_SVREXIST, "SIPE_SVREXIST"},

		{SIPE_TDAUSERERR, "SIPE_TDAUSERERR"},
		{SIPE_TAGNOTSUBSCRIPT, "SIPE_TAGNOTSUBSCRIPT"},
		{SIPE_TDAUSERFULL, "SIPE_TDAUSERFULL"},
		{SIPE_TDANOUSERID, "SIPE_TDANOUSERID"} };
	T_U32 i, un = sizeof(errcode) / sizeof(MSGCODE);
	for (i = 0; i < un; i++)
		if (errcode[i].icode == icode) return errcode[i].sdes;
	return pnull;
};